buckets: 
hooks:
  - class: PrintModelAnalysisHook
  - class: MetadataCaptureHook
  - class: TrainSampleHook
    params:
      every_n_steps: 1000
  - class: TokensPerSecondCounter
    params:
       every_n_steps: 100
